"""Markdown report output."""

from typing import Optional

from ..results import AuditResult, Status
from .encoding import stdout_can_encode


class MarkdownReporter:
    STATUS_EMOJI = {
        Status.PASS: "✅",
        Status.FAIL: "❌",
        Status.WARN: "⚠️",
        Status.SKIP: "⏭️",
        Status.ERROR: "💥",
    }
    STATUS_ASCII = {
        Status.PASS: "PASS",
        Status.FAIL: "FAIL",
        Status.WARN: "WARN",
        Status.SKIP: "SKIP",
        Status.ERROR: "ERROR",
    }
    SCORE_BADGES = {"green": "🟢", "yellow": "🟡", "red": "🔴"}

    def __init__(self, unicode_glyphs: Optional[bool] = None):
        if unicode_glyphs is None:
            # Auto-detect: a redirected stream on Windows may use a legacy
            # codec (e.g. cp1252) that cannot encode the emoji.
            sample = "".join(self.STATUS_EMOJI.values()) + "".join(
                self.SCORE_BADGES.values()
            )
            unicode_glyphs = stdout_can_encode(sample)
        self.unicode_glyphs = unicode_glyphs
        self.status_icons = self.STATUS_EMOJI if unicode_glyphs else self.STATUS_ASCII

    def _badge(self, score: float) -> str:
        level = "green" if score >= 80 else "yellow" if score >= 60 else "red"
        if not self.unicode_glyphs:
            return ""
        return self.SCORE_BADGES[level] + " "

    def report(self, result: AuditResult) -> str:
        lines = [
            "# Infrastructure Audit Report",
            "",
            f"**Target:** `{result.target}`  ",
            f"**OS:** {result.os_type}  ",
            f"**Date:** {result.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}  ",
            "",
            "## Summary",
            "",
        ]
        score = result.compliance_score
        icons = self.status_icons
        lines.extend(
            [
                "| Metric | Value |",
                "|--------|-------|",
                f"| Compliance Score | {self._badge(score)}**{score}%** |",
                f"| Passed | {icons[Status.PASS]} {result.passed} |",
                f"| Failed | {icons[Status.FAIL]} {result.failed} |",
                f"| Warnings | {icons[Status.WARN]} {result.warnings} |",
                f"| Skipped | {icons[Status.SKIP]} {result.skipped} |",
                f"| Total | {result.total} |",
                "",
            ]
        )
        failures = [c for c in result.checks if c.status == Status.FAIL]
        if failures:
            failed_heading = (
                "## ❌ Failed Checks" if self.unicode_glyphs else "## Failed Checks"
            )
            lines.extend([failed_heading, ""])
            for check in failures:
                lines.extend(
                    [
                        f"### {check.name}",
                        "",
                        f"- **Severity:** {check.severity.value.upper()}",
                        f"- **Status:** {check.message}",
                    ]
                )
                if check.remediation:
                    lines.append(f"- **Remediation:** `{check.remediation}`")
                lines.append("")
        lines.extend(
            [
                "## All Checks",
                "",
                "| Status | Check | Severity | Message |",
                "|--------|-------|----------|---------|",
            ]
        )
        for check in result.checks:
            icon = icons.get(check.status, "?" if not self.unicode_glyphs else "❓")
            lines.append(
                f"| {icon} | {check.name} | {check.severity.value} | {check.message} |"
            )
        if result.exit_code == 0:
            exit_status = (
                f"{icons[Status.PASS]} PASSED" if self.unicode_glyphs else "PASSED"
            )
        else:
            exit_status = (
                f"{icons[Status.FAIL]} FAILED" if self.unicode_glyphs else "FAILED"
            )
        lines.extend(
            [
                "",
                "---",
                f"**Exit Code:** `{result.exit_code}` ({exit_status})",
                "",
                "*Generated by [infra-auditor](https://github.com/tommieseals/infra-auditor)*",
            ]
        )
        return "\n".join(lines)

    def save(self, result: AuditResult, path: str):
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.report(result))
